### ISSUE TITLE
self return type

### ISSUE THREAD

**Issue by bendavies** [nikic/TypeUtil#4]
Hey there!

Thanks for the great tool.
What do you think result be of type hinting methods which specify 
`@return self` or `@return $this`
should be?

At the moment, we'll get:
```
Collecting context...
PHP Fatal error:  Uncaught PhpParser\Error: '\self' is an invalid class name on line 12 in .../nikic/php-parser/lib/PhpParser/NameContext.php:107
```

Thanks!

**Comment by nikic** [comment]
I've fixed the bug that caused the `\self` to be generated in PHP-Parser (https://github.com/nikic/PHP-Parser/commit/19dde1363e8bd83e98bc2320ecc42b61e379255d) and bumped the dependency. However, there is still an issue here, because the current handling of `self` does not treat the variance rules correctly. For example

```php
class A {
    /** @return self */
    public function foo() {}
}

class B extends A {
    /** @return self */
    public function foo() {}
}
```

currently generates

```php
class A {
    /** @return self */
    public function foo() : self {}
}

class B extends A {
    /** @return self */
    public function foo() : self {}
}
```

but should generate

```php
class A {
    /** @return self */
    public function foo() : self {}
}

class B extends A {
    /** @return self */
    public function foo() : A {}
}
```

to avoid a variance error.

**Comment by bendavies** [comment]
Nice one, thanks!
Do you want to keep this issue open to track the variance problem?

**Comment by nikic** [comment]
The issue with variance handling has been fixed in https://github.com/nikic/TypeUtil/commit/6de4fb257688372d2c078927a94ac640e7529cfd, so closing this now.
